services:
  # webapp:
  #   image: python:3.12-slim
  #   container_name: llm-response-demo-container
  #   working_dir: /app
  #   ports:
  #     - "3000:8000"
  #   environment:
  #     - DMR_BASE_URL=http://host.docker.internal:12434
  #     - MODEL_NAME=hf.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q3_K_M
  #     - CONTEXT_SIZE=4096
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   volumes:
  #     - ./llm_response_demo:/app
  #   command: sh -c "pip install flask requests && python app.py"
  #   restart: unless-stopped

models:
  llm:
    model: hf.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q3_K_M
    context_size: 4096


# Funktionierende Modelle:
# Qwen2.5 coder 7B instruct Q3
# hf.co/Qwen/Qwen2.5-Coder-7B-Instruct-GGUF:Q3_K_M

# Qwen2.5 7B Instruct Q4
# hf.co/Qwen/Qwen2.5-7B-Instruct-GGUF:Q4_K_M