<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Chat.Core/Chat.Core.csproj" />
    <ProjectReference Include="../Chat.Store.Sqlite/Chat.Store.Sqlite.csproj" />
    <ProjectReference Include="../Chat.Adapter.ModelRunner/Chat.Adapter.ModelRunner.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="resources\system_prompt.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
