// <auto-generated />
using System;
using Chat.Store.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Chat.Store.Sqlite.Migrationen
{
    [DbContext(typeof(ChatDbContext))]
    partial class ChatDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Chat.Store.Sqlite.AntwortDatensatz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DauerMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErstelltAm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Fall")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Grund")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NachrichtId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Zustand")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NachrichtId")
                        .IsUnique();

                    b.ToTable("Antwort", (string)null);
                });

            modelBuilder.Entity("Chat.Store.Sqlite.NachrichtDatensatz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UnterhaltungId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Zeit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UnterhaltungId");

                    b.ToTable("Nachricht", (string)null);
                });

            modelBuilder.Entity("Chat.Store.Sqlite.UnterhaltungDatensatz", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErstelltAm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Unterhaltung", (string)null);
                });

            modelBuilder.Entity("Chat.Store.Sqlite.AntwortDatensatz", b =>
                {
                    b.HasOne("Chat.Store.Sqlite.NachrichtDatensatz", null)
                        .WithOne("Antwort")
                        .HasForeignKey("Chat.Store.Sqlite.AntwortDatensatz", "NachrichtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chat.Store.Sqlite.NachrichtDatensatz", b =>
                {
                    b.HasOne("Chat.Store.Sqlite.UnterhaltungDatensatz", null)
                        .WithMany("Nachrichten")
                        .HasForeignKey("UnterhaltungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Chat.Store.Sqlite.NachrichtDatensatz", b =>
                {
                    b.Navigation("Antwort")
                        .IsRequired();
                });

            modelBuilder.Entity("Chat.Store.Sqlite.UnterhaltungDatensatz", b =>
                {
                    b.Navigation("Nachrichten");
                });
#pragma warning restore 612, 618
        }
    }
}
